function formatSpecialistMarkdown(insight) {
  const confidencePct = Math.round((insight.confidence || 0) * 100);
  const lines = [
    `## ${insight.agent}`,
    "",
    insight.summary,
    "",
    `**Confidence:** ${confidencePct}%`,
  ];

  if (insight.findings?.length) {
    lines.push("", "### Key Findings", "");
    insight.findings.forEach((finding) => {
      lines.push(`- **${finding.title}** (${finding.impact} impact): ${finding.description}`);
    });
  }

  if (insight.recommendations?.length) {
    lines.push("", "### Recommendations", "");
    insight.recommendations.forEach((rec, index) => {
      lines.push(`${index + 1}. ${rec}`);
    });
  }

  return lines.join("\n");
}

function formatExecutiveReportMarkdown(report) {
  const confidencePct = Math.round((report.confidence || 0) * 100);
  const lines = [
    `# ${report.title || "Executive Report"}`,
    "",
    `## Executive Summary`,
    "",
    report.executiveSummary,
    "",
    `**Business Health Score:** ${report.businessHealth}/100`,
    `**Confidence Score:** ${confidencePct}%`,
    "",
    "## Financial Analysis",
    "",
    report.financialAnalysis,
    "",
    "## Marketing Analysis",
    "",
    report.marketingAnalysis,
    "",
    "## Business Analysis",
    "",
    report.businessAnalysis,
    "",
    "## Customer Support Analysis",
    "",
    report.customerSupportAnalysis,
    "",
    "## Top Risks",
    "",
  ];

  report.topRisks.forEach((risk, index) => lines.push(`${index + 1}. ${risk}`));

  lines.push("", "## Priority Actions", "");
  report.priorityActions.forEach((action, index) => lines.push(`${index + 1}. ${action}`));

  lines.push("", "## 30-Day Action Plan", "");
  report.actionPlan30Day.forEach((step, index) => lines.push(`${index + 1}. ${step}`));

  lines.push(
    "",
    "## Expected Business Impact",
    "",
    report.expectedImpact,
    "",
    "---",
    "",
    "*Generated by ExecOS AI*"
  );

  return lines.join("\n");
}

module.exports = {
  formatSpecialistMarkdown,
  formatExecutiveReportMarkdown,
};
