/**
 * Defines the strict metadata and record schemas for the vector database.
 * This guarantees consistency for all documents processed through the pipeline.
 */
export interface IVectorMetadata {
  /**
   * Unique identifier for the workspace (tenant). 
   * Crucial for data isolation.
   */
  workspaceId: string;

  /**
   * Unique identifier connecting this chunk back to the source document in the primary database.
   */
  documentId: string;

  /**
   * Unique identifier specifically for this chunk.
   */
  chunkId: string;

  /**
   * The sequential index of this chunk within the original document (e.g., 0, 1, 2).
   */
  chunkIndex: number;

  /**
   * The business category or original extension of the document (e.g., "invoice", "contract").
   */
  documentType: string;

  /**
   * The MIME type of the original file (e.g., "application/pdf").
   */
  mimeType: string;

  /**
   * The human-readable title of the document.
   */
  title: string;

  /**
   * The raw text content of the chunk. Stored directly to prevent a secondary SQL lookup.
   */
  content: string;

  /**
   * An open-ended JSON object to store any parser-specific or custom business metadata.
   */
  metadata?: Record<string, any>;

  /**
   * Timestamp of when this chunk was created.
   */
  createdAt: string;

  /**
   * Timestamp of the most recent update to this chunk's data.
   */
  updatedAt: string;
}

/**
 * The final record structure prepared for Vector Storage.
 */
export interface IVectorRecord {
  /**
   * The globally unique identifier for the vector record.
   */
  id: string;

  /**
   * The high-dimensional numerical vector generated by the embedding provider.
   */
  embedding: number[];

  /**
   * The comprehensive metadata payload.
   */
  metadata: Omit<IVectorMetadata, 'embedding'>;
}
