import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import {
  ArrowLeft,
  Loader2,
  AlertCircle,
} from 'lucide-react';
import { getReportById, type ReportDetail } from '../services/reportService';
import ExecutiveReportView from '../components/reports/ExecutiveReportView';

export default function ReportDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [report, setReport] = useState<ReportDetail | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!id) return;

    setIsLoading(true);
    getReportById(id)
      .then(setReport)
      .catch((err: unknown) => {
        const message =
          err && typeof err === 'object' && 'response' in err
            ? (err as { response?: { data?: { error?: string; details?: string; message?: string } } }).response?.data
            : null;
        setError(
          message?.error && message?.details
            ? `${message.error} ${message.details}`
            : message?.error || message?.details || message?.message || 'Failed to load report.'
        );
      })
      .finally(() => setIsLoading(false));
  }, [id]);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh] text-[#cbc3d7]">
        <Loader2 className="w-6 h-6 animate-spin text-violet-300 mr-2" />
        Loading report...
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="max-w-3xl mx-auto px-4 py-12">
        <div className="rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-red-300 flex items-start gap-2">
          <AlertCircle size={16} className="mt-0.5" />
          <p>{error || 'Report not found.'}</p>
        </div>
        <button
          onClick={() => navigate('/reports')}
          className="mt-4 text-sm text-violet-300 hover:text-violet-200"
        >
          ← Back to Reports
        </button>
      </div>
    );
  }

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 py-6 pb-20">
      <div className="sticky top-0 z-20 -mx-4 sm:-mx-6 px-4 sm:px-6 py-3 bg-[#0b1326]/90 backdrop-blur-xl border-b border-white/10 mb-6 flex items-center justify-between gap-3">
        <button
          onClick={() => navigate('/reports')}
          className="flex items-center gap-2 text-sm text-[#cbc3d7] hover:text-white transition"
        >
          <ArrowLeft size={16} /> Back
        </button>
        <span className="text-xs text-[#958ea0] hidden sm:inline">Generated by ExecOS AI</span>
      </div>

      <div className="bg-[rgba(23,31,51,0.72)] backdrop-blur-xl border border-white/10 rounded-2xl p-5 sm:p-8">
        <div className="mb-6">
          <h1 className="text-2xl sm:text-3xl font-bold text-[#dae2fd] mb-2">{report.title}</h1>
          <div className="p-4 rounded-xl bg-white/5 border border-white/10">
            <p className="text-[10px] uppercase tracking-wider text-[#958ea0] mb-1">Original Prompt</p>
            <p className="text-sm text-[#dae2fd]">{report.prompt}</p>
          </div>
        </div>

        <ExecutiveReportView report={report} />
      </div>
    </div>
  );
}
